# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "LV-Deploy"

on:
  push:
    branches: [ feature/lvtest ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ feature/lvtest ]

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: echo "Build/Install dependencies"
    
    - name: Code quality
      run: echo "scan code/check standard"

    - name: Tests
      run: echo "yarn test"

    - name: Deploy
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      run: |
        ssh-keyscan -H 54.245.162.99 >> ~/.ssh/known_hosts
        echo "deploy"
    - run: echo "Nofify"
